name: ${DN_TARGET_COMPOSE_PROJECT_NAME}

services:

  # ====Fast test service=======================================================================
#  dependencies-test:
#    extends:
#      file: ../global-service-builder/docker-compose.global-service.build.yaml
#      service: global-service-builder
#    build:
#      context: .
#      dockerfile: Dockerfile.test_remote
#      args:
#        BASE_IMAGE: nvcr.io/nvidia/l4t-jetpack
#        BASE_IMAGE_TAG: r35.2.1
#    image: ${DN_HUB:?err}/dependencies-test:r35.2.1

  # ====Dockerized-NorLab dependencies=============================================================
  dependencies-core:
    extends:
      file: ../global-service-builder/docker-compose.global-service.build.yaml
      service: global-service-builder
    build:
      context: .
      dockerfile: Dockerfile.core
      args:
        BASE_IMAGE: ${DEPENDENCIES_BASE_IMAGE:?err}
        BASE_IMAGE_TAG: ${DEPENDENCIES_BASE_IMAGE_TAG:?err}
    image: ${DN_HUB:?err}/dependencies-core:${DN_IMAGE_TAG:?err}

  dependencies-prompt:
    extends: dependencies-core
    build:
      dockerfile: Dockerfile.prompt
      args:
        BASE_IMAGE: ${DN_HUB:?err}/dependencies-core
        BASE_IMAGE_TAG: ${DN_IMAGE_TAG:?err}
    environment:
      DN_ACTIVATE_POWERLINE_PROMT: false
      DN_CONTAINER_NAME: IamInteractive
    container_name: IamInteractive
    image: ${DN_HUB:?err}/dependencies-prompt:${DN_IMAGE_TAG:?err}
    depends_on:
      - dependencies-core

  dependencies-python-science-stack:
    extends: dependencies-core
    build:
      dockerfile: Dockerfile.python-science-stack
      args:
        BASE_IMAGE: ${DN_HUB:?err}/dependencies-prompt
        BASE_IMAGE_TAG: ${DN_IMAGE_TAG:?err}
    image: ${DN_HUB:?err}/dependencies-python-science-stack:${DN_IMAGE_TAG:?err}
    depends_on:
      - dependencies-prompt

  dependencies-ros2-custom:
    extends: dependencies-core
    build:
      dockerfile: Dockerfile.ros2-dn-custom
      args:
        BASE_IMAGE: ${DN_HUB:?err}/dependencies-python-science-stack
        BASE_IMAGE_TAG: ${DN_IMAGE_TAG:?err}
      tags:
        - ${DN_HUB:?err}/dn-dependencies:${DN_IMAGE_TAG:?err}
    image: ${DN_HUB:?err}/dependencies-ros2-custom:${DN_IMAGE_TAG:?err}
    depends_on:
      - dependencies-python-science-stack
