name: ${DN_COMPOSE_NAME}

services:

  # ====Fast test service==========================================================================
#  dependencies-test:
#    extends:
#      file: ../global-service-builder/docker-compose.global-service.build.yaml
#      service: global-service-builder
#    build:
#      context: .
#      dockerfile: Dockerfile.test
#      args:
#        BASE_IMAGE: nvcr.io/nvidia/l4t-jetpack
#        BASE_IMAGE_TAG: r35.2.1
#    image: ${DN_HUB:?err}/dn-dependencies-test:r35.2.1

  # ====Dockerized-NorLab dependencies=============================================================

  # ....dependencies-core..........................................................................

  dependencies-main: # ›› no push build service
    extends:
      file: ../global-service-builder/docker-compose.global-service.build.yaml
      service: global-service-builder
    build:
      context: .
      dockerfile: Dockerfile.core
      args:
        BASE_IMAGE: ${DEPENDENCIES_BASE_IMAGE:?err}
        BASE_IMAGE_TAG: ${DEPENDENCIES_BASE_IMAGE_TAG:?err}
        TAG_VERSION: ${TAG_VERSION:?err}
        ROS_DISTRO: ${ROS_DISTRO:?err}
        ROS_ROOT: ${ROS_ROOT:?err}
        ROS_PYTHON_VERSION: ${ROS_PYTHON_VERSION:?err}
        RMW_IMPLEMENTATION: ${RMW_IMPLEMENTATION:?err}
        # The following env var does not appear in every jetson-container ros base images
        LD_PRELOAD: ${LD_PRELOAD}
        OPENBLAS_CORETYPE: ${OPENBLAS_CORETYPE}

  dependencies-squashed-base-image-tester:
    extends: dependencies-main
    build:
      target: squashed-base-image-tester
    depends_on:
      - dependencies-main

  dependencies-core:
    extends: dependencies-main
    image: ${DN_HUB:?err}/dn-dependencies-core:${DN_IMAGE_TAG:?err}
    depends_on:
      - dependencies-main

  # ....dependencies-prompt........................................................................
  dependencies-prompt:
    extends: dependencies-core
    build:
      dockerfile: Dockerfile.prompt
      args:
        BASE_IMAGE: ${DN_HUB:?err}/dn-dependencies-core
        BASE_IMAGE_TAG: ${DN_IMAGE_TAG:?err}
    environment:
      DN_ACTIVATE_POWERLINE_PROMT: false
      DN_CONTAINER_NAME: IamInteractive
    container_name: IamInteractive
    image: ${DN_HUB:?err}/dn-dependencies-prompt:${DN_IMAGE_TAG:?err}
    depends_on:
      - dependencies-core

  # ....dependencies-python-science-stack..........................................................
  dependencies-python-science-stack:
    extends: dependencies-core
    build:
      dockerfile: Dockerfile.python-science-stack
      args:
        BASE_IMAGE: ${DN_HUB:?err}/dn-dependencies-prompt
        BASE_IMAGE_TAG: ${DN_IMAGE_TAG:?err}
    image: ${DN_HUB:?err}/dn-dependencies-python-science-stack:${DN_IMAGE_TAG:?err}
    depends_on:
      - dependencies-prompt

  # ....dependencies-ros2-custom...................................................................
  dependencies-ros2-custom-main: # ›› no push build service
    extends: dependencies-main
    build:
      dockerfile: Dockerfile.ros2-dn-custom
      args:
        BASE_IMAGE: ${DN_HUB:?err}/dn-dependencies-python-science-stack
        BASE_IMAGE_TAG: ${DN_IMAGE_TAG:?err}
    depends_on:
      - dependencies-python-science-stack

  dependencies-ros2-custom-tester:
    extends: dependencies-ros2-custom-main
    build:
      target: test
    depends_on:
      - dependencies-ros2-custom-main

  dependencies-ros2-custom:
    extends: dependencies-ros2-custom-main
    build:
      tags:
        - ${DN_HUB:?err}/dn-dependencies:${DN_IMAGE_TAG:?err}
    image: ${DN_HUB:?err}/dn-dependencies-ros2-custom:${DN_IMAGE_TAG:?err}
    depends_on:
      - dependencies-ros2-custom-main

