version: "3.9"
services:
  ros2_humble:
    image: norlabsnow/norlab-ros2-humble:arm64-l4t-r35.2.1
    build:
      context: ./Docker/norlab-ros2/humble
      dockerfile: ./Dockerfile
      args:
        BASE_IMAGE: dustynv/ros:humble-pytorch-l4t-r35.2.1
        DS_IMAGE_ARCHITECTURE: arm64-l4t
        DS_ROS_PKG: ros_base # see comment in dockerfile
  dependencies_core:
    image: norlabsnow/norlab-ros2-humble-dependencies-wo-services:arm64-l4t-r35.2.1
    build:
      context: ./Docker
      dockerfile: ./norlab-ros2/dependencies/Dockerfile
      args:
        BASE_IMAGE: norlabsnow/norlab-ros2-humble:arm64-l4t-r35.2.1
    depends_on:
      - ros2_humble
  dependencies_user_services:
    image: norlabsnow/norlab-ros2-humble-dependencies:arm64-l4t-r35.2.1
    build:
      context: ./Docker
      dockerfile: ./norlab-ros2/dependencies/user_services/Dockerfile
      args:
        BASE_IMG_TAG: arm64-l4t-r35.2.1
    depends_on:
      - dependencies_core
  dn_project:
    image: norlabsnow/project_f1tenth:arm64-l4t-r35.2.1
    build:
      context: ./Docker/norlab-ros2/dn_project/project_f1tenth
      dockerfile: ./Dockerfile
      args:
        BASE_IMG_TAG: arm64-l4t-r35.2.1
        DN_TARGET_PROJECT_SRC_REPO: NorLab_MPPI
    depends_on:
      - dependencies_user_services
  develop:
#    image: norlabsnow/norlab-ros2-humble-develop:arm64-l4t-r35.2.1
    image: norlabsnow/norlab-ros2-f1tenth-develop:arm64-l4t-r35.2.1
    build:
      context: ./Docker/norlab-ros2/develop
      dockerfile: ./Dockerfile
      args:
        BASE_IMG_TAG: arm64-l4t-r35.2.1
#        DS_HOST_TYPE: XavierNX # Option: Local (Not used now)
    depends_on:
      - dn_project











