version: "3.9"
services:
  ros_foxy_torch:
    image: ${DN_HUB}/norlab-ros:foxy-pytorch-${DN_IMAGE_ARCHITECTURE}-r35.2.1
    build:
      context: Docker/norlab-ros2/ROS
      dockerfile: ./Dockerfile
      args:
        # (!) L4T container tags (e.g. r35.2.1) should match the L4T version on the Jetson otherwize cuda driver won't be accessible (ref https://github.com/dusty-nv/jetson-containers#pre-built-container-images )
        BASE_IMAGE: dustynv/ros:foxy-pytorch-l4t-r35.2.1
#        docker pull dustynv/ros:foxy-pytorch-l4t-r35.2.1
        DN_IMAGE_ARCHITECTURE: ${DN_IMAGE_ARCHITECTURE} # arm64-l4t, arm64-darwin, x86
        DN_ROS_PKG: ros_base # inactive, see comment in dockerfile
  dependencies_core:
    image: ${DN_HUB}/norlab-ros-dependencies:foxy-pytorch-${DN_IMAGE_ARCHITECTURE}-r35.2.1
    build:
      context: ./Docker
      dockerfile: ./norlab-ros2/dependencies/Dockerfile
      args:
        BASE_IMAGE: ${DN_HUB}/norlab-ros
        DN_BASE_IMG_TAG: foxy-pytorch-${DN_IMAGE_ARCHITECTURE}-r35.2.1
    depends_on:
      - ros_foxy_torch
  dependencies_user_services:
    image: ${DN_HUB}/norlab-ros-dependencies-user-services:foxy-pytorch-${DN_IMAGE_ARCHITECTURE}-r35.2.1
    build:
      context: ./Docker
      dockerfile: ./norlab-ros2/dependencies/user_services/Dockerfile
      args:
        DN_BASE_IMG_TAG: foxy-pytorch-${DN_IMAGE_ARCHITECTURE}-r35.2.1
    depends_on:
      - dependencies_core
  dn_project:
    image: ${DN_PROJECT_HUB}/${DN_PROJECT_IMAGE_NAME}:foxy-pytorch-${DN_IMAGE_ARCHITECTURE}-r35.2.1
    build:
      context: ./Docker/norlab-ros2/dn_project
      dockerfile: ./Dockerfile
      args:
        DN_BASE_IMG_TAG: foxy-pytorch-${DN_IMAGE_ARCHITECTURE}-r35.2.1
        DN_TARGET_PROJECT_SRC_DOMAIN: ${DN_TARGET_PROJECT_SRC_DOMAIN}   # norlab-ulaval
        DN_TARGET_PROJECT_SRC_REPO: ${DN_TARGET_PROJECT_SRC_REPO}   # NorLab_MPPI
    depends_on:
      - dependencies_user_services
  develop:
    image: ${DN_PROJECT_HUB}/${DN_PROJECT_IMAGE_NAME}-develop:foxy-pytorch-${DN_IMAGE_ARCHITECTURE}-r35.2.1
    build:
      context: ./Docker/norlab-ros2/develop
      dockerfile: ./Dockerfile
      args:
        DN_HUB: ${DN_PROJECT_HUB}   # norlabsnow
        DN_PROJECT_IMAGE_NAME: ${DN_PROJECT_IMAGE_NAME}   # norlab-ros-project-template
        DN_BASE_IMG_TAG: foxy-pytorch-${DN_IMAGE_ARCHITECTURE}-r35.2.1
#        DN_TARGET_PROJECT_SRC_DOMAIN: ${DN_TARGET_PROJECT_SRC_DOMAIN}
#        DN_TARGET_PROJECT_SRC_REPO: ${DN_TARGET_PROJECT_SRC_REPO}
#        DS_HOST_TYPE: XavierNX # Option: Local (Not used now)
    depends_on:
      - dn_project

#  deploy:
#    image: ${DN_PROJECT_HUB}/${DN_PROJECT_IMAGE_NAME}-deploy:foxy-pytorch-${DN_IMAGE_ARCHITECTURE}-r35.2.1
#    build:
#      context: ./Docker/norlab-ros2/deploy
#      dockerfile: ./Dockerfile
#      args:
#         DN_HUB: ${DN_PROJECT_HUB}   # norlabsnow
#         DN_PROJECT_IMAGE_NAME: ${DN_PROJECT_IMAGE_NAME}   # norlab-ros-project-template
#         DN_BASE_IMG_TAG: foxy-pytorch-${DN_IMAGE_ARCHITECTURE}-r35.2.1
##         DS_HOST_TYPE: XavierNX # Option: Local (Not used now)
##         DN_DEPLOY_REPO_BRANCH: master
#    depends_on:
#      - dn_project







