version: "3.9"
services:
  ros2_humble:
    image: norlabsnow/norlab-ros2-humble:arm64-l4t-r35.2.1
    build:
      context: ./Docker/norlab-ros2/humble
      dockerfile: ./Dockerfile
      args:
        BASE_IMAGE: dustynv/ros:humble-pytorch-l4t-r35.2.1
        DS_IMAGE_ARCHITECTURE: arm64-l4t
        DS_ROS_PKG: ros_base # see comment in dockerfile






