services:

  # ====Dockerized-NorLab control =================================================================

  # ....dn-control-deep-learning...................................................................
  dn-control-deep-learning:
#    extends:
#      file: docker-compose.dn-control.build.yaml
#      service: dn-control
    extends:
      file: "../global/docker-compose.global.yaml"
      service: global-service-builder-config
    pull_policy: build
    build:
      context: dn-control-deep-learning
      args:
        BASE_IMAGE: ${DN_HUB:?err}/dockerized-norlab-dependencies-full
        BASE_IMAGE_TAG: ${DN_IMAGE_TAG:?err}
    image: ${DN_HUB:?err}/dockerized-norlab-control-deep-learning:${DN_IMAGE_TAG:?err}

  # ....dn-control-deep-rl.........................................................................
  dn-control-deep-rl-main:
    extends:
      file: "../global/docker-compose.global.yaml"
      service: global-service-builder-config
    build:
      context: dn-control-deep-rl
      target: main
      args:
        BASE_IMAGE: ${DN_HUB:?err}/dockerized-norlab-control-deep-learning
        BASE_IMAGE_TAG: ${DN_IMAGE_TAG:?err}
    depends_on:
      - dn-control-deep-learning

  dn-control-deep-rl-tester:
    extends:
      service: dn-control-deep-rl-main
    build:
      target: test
    depends_on:
      - dn-control-deep-rl-main

  dn-control-deep-rl:
    extends:
      service: dn-control-deep-rl-main
    build:
      target: final
    image: ${DN_HUB:?err}/dockerized-norlab-control-deep-rl:${DN_IMAGE_TAG:?err}
    depends_on:
      - dn-control-deep-rl-tester

  # ....dn-control-deep-rl-openai-gym..............................................................
  dn-control-deep-rl-openai-gym:
    extends:
      file: "../global/docker-compose.global.yaml"
      service: global-service-builder-config
    pull_policy: build
    build:
      context: dn-control-openai-gym
      target: main
      args:
        BASE_IMAGE: ${DN_HUB:?err}/dockerized-norlab-control-deep-rl
        BASE_IMAGE_TAG: ${DN_IMAGE_TAG:?err}
    image: ${DN_HUB:?err}/dockerized-norlab-control-deep-rl-openai-gym:${DN_IMAGE_TAG:?err}
    depends_on:
      - dn-control-deep-rl

  dn-control-deep-rl-openai-gym-tester:
    extends:
      service: dn-control-deep-rl-openai-gym
    build:
      target: test
    depends_on:
      - dn-control-deep-rl-openai-gym

  # ....dn-control-deep-rl-f1tenth-gym.............................................................
  dn-control-deep-rl-f1tenth-gym-main:
    extends:
      file: "../global/docker-compose.global.yaml"
      service: global-service-builder-config
    build:
      context: dn-control-f1tenth-gym
      target: main
      args:
        BASE_IMAGE: ${DN_HUB:?err}/dockerized-norlab-control-deep-rl-openai-gym
        BASE_IMAGE_TAG: ${DN_IMAGE_TAG:?err}
    pull_policy: build
    depends_on:
      - dn-control-deep-rl-openai-gym

  dn-control-deep-rl-f1tenth-gym-tester:
    extends:
      service: dn-control-deep-rl-f1tenth-gym-main
    build:
      target: test
    depends_on:
      - dn-control-deep-rl-f1tenth-gym-main

  dn-control-deep-rl-f1tenth-gym:
    extends:
      service: dn-control-deep-rl-f1tenth-gym-main
    build:
      target: final
      tags:
        - ${DN_HUB:?err}/dockerized-norlab-control-deep-rl-f1tenth:${DN_IMAGE_TAG:?err}
    image: ${DN_HUB:?err}/dockerized-norlab-control-deep-rl-f1tenth-gym:${DN_IMAGE_TAG:?err}
    depends_on:
      - dn-control-deep-rl-f1tenth-gym-tester

