name: ${DN_TARGET_COMPOSE_PROJECT_NAME}

services:

  # ====Dockerized-NorLab control =================================================================
  dn-control:
    extends:
      file: ../global-service-builder/docker-compose.global-service.build.yaml
      service: global-service-builder
    build:
      context: dn-control
      args:
        BASE_IMAGE: ${DN_HUB:?err}/dn-dependencies
        BASE_IMAGE_TAG: ${DN_IMAGE_TAG:?err}
    image: ${DN_HUB:?err}/dn-control:${DN_IMAGE_TAG:?err}

  dn-control-gym:
    extends: dn-control
    build:
      context: dn-control-gym
      args:
        BASE_IMAGE: ${DN_HUB:?err}/dn-control
    image: ${DN_HUB:?err}/dn-control-gym:${DN_IMAGE_TAG:?err}
    depends_on:
      - dn-control

#  dn-control-f1tenth:
#    extends: dn-control
#    build:
#      context: dn-control-f1tenth
#      args:
#        BASE_IMAGE: ${DN_HUB:?err}/dn-control-gym
#    image: ${DN_HUB:?err}/dn-control-f1tenth:${DN_IMAGE_TAG:?err}
#    depends_on:
#      - dn-control-gym
#
