services:

  # ====Dockerized-NorLab control =================================================================
  dn-control-deep-learning:
#    extends:
#      file: docker-compose.dn-control.build.yaml
#      service: dn-control
    extends:
      file: "../global/docker-compose.global.yaml"
      service: global-service-builder-config
#    pull_policy: build
    build:
      context: dn-control-deep-learning
      args:
        BASE_IMAGE: ${DN_HUB:?err}/dockerized-norlab-dependencies-full
        BASE_IMAGE_TAG: ${DN_IMAGE_TAG:?err}
    image: ${DN_HUB:?err}/dockerized-norlab-control-deep-learning:${DN_IMAGE_TAG:?err}

  dn-control-deep-rl:
    extends:
      service: dn-control-deep-learning
    build:
      context: dn-control-deep-rl
      args:
        BASE_IMAGE: ${DN_HUB:?err}/dockerized-norlab-control-deep-learning
    image: ${DN_HUB:?err}/dockerized-norlab-control-deep-rl:${DN_IMAGE_TAG:?err}
    depends_on:
      - dn-control-deep-learning

  dn-control-deep-rl-openai-gym:
#    extends:
#      service: dn-control-deep-learning
    extends:
      file: "../global/docker-compose.global.yaml"
      service: global-service-builder-config
#    pull_policy: build
    build:
      context: dn-control-openai-gym
      args:
        BASE_IMAGE: ${DN_HUB:?err}/dockerized-norlab-control-deep-rl
        BASE_IMAGE_TAG: ${DN_IMAGE_TAG:?err}
    image: ${DN_HUB:?err}/dockerized-norlab-control-deep-rl-openai-gym:${DN_IMAGE_TAG:?err}
    depends_on:
      - dn-control-deep-rl

  dn-control-deep-rl-f1tenth:
    extends:
      service: dn-control-deep-rl-openai-gym
    build:
      context: dn-control-f1tenth
      args:
        BASE_IMAGE: ${DN_HUB:?err}/dockerized-norlab-control-deep-rl-openai-gym
    pull_policy: build
    image: ${DN_HUB:?err}/dockerized-norlab-control-deep-rl-f1tenth:${DN_IMAGE_TAG:?err}
    depends_on:
      - dn-control-deep-rl-openai-gym


#  dn-control-torchrl:
#    extends:
#      service: dn-control-deep-rl-openai-gym
#    build:
#      context: dn-control-torchrl
#      args:
#        BASE_IMAGE: ${DN_HUB:?err}/dockerized-norlab-control-deep-rl
#    image: ${DN_HUB:?err}/dockerized-norlab-control-torchrl:${DN_IMAGE_TAG:?err}
#    depends_on:
#      - dn-control-deep-rl
