


services:

  # ====Dockerized-NorLab control =================================================================
  dn-control:
    extends:
      file: ../global-service-builder/docker-compose.global-service.build.yaml
      service: global-service-builder-config
    build:
      context: dn-control
      args:
        BASE_IMAGE: ${DN_HUB:?err}/dockerized-norlab-dependencies-full
        BASE_IMAGE_TAG: ${DN_IMAGE_TAG:?err}
    image: ${DN_HUB:?err}/dockerized-norlab-control:${DN_IMAGE_TAG:?err}

#  dn-control-gym:
#    extends: dn-control
#    build:
#      context: dn-control-gym
#      args:
#        BASE_IMAGE: ${DN_HUB:?err}/dockerized-norlab-control
#    image: ${DN_HUB:?err}/dockerized-norlab-control-gym:${DN_IMAGE_TAG:?err}
#    depends_on:
#      - dn-control

#  # (!) Install problem, skipping for now, will use the 'dockerized-norlab-control-deep-rl-f1tenth' image in the mean time
#  dn-control-f1tenth:
#    extends: dn-control
#    build:
#      context: dn-control-f1tenth
#      args:
#        BASE_IMAGE: ${DN_HUB:?err}/dockerized-norlab-control
##      no_cache: true
#    image: ${DN_HUB:?err}/dockerized-norlab-control-f1tenth:${DN_IMAGE_TAG:?err}
##    pull_policy: build
#    depends_on:
#      - dn-control
#
