name: ${DN_TARGET_COMPOSE_PROJECT_NAME}

services:

  # ====Dockerized-NorLab perception ==============================================================
  dn-perception:
    extends:
      file: ../global-service-builder/docker-compose.global-service.build.yaml
      service: global-service-builder
    build:
      context: dn-perception
      args:
        BASE_IMAGE: ${DN_HUB:?err}/dn-dependencies
        BASE_IMAGE_TAG: ${DN_IMAGE_TAG:?err}
    image: ${DN_HUB:?err}/dn-perception:${DN_IMAGE_TAG:?err}

  dn-perception-libpointmatcher:
    extends: dn-perception
    build:
      context: dn-perception-libpointmatcher
      args:
        BASE_IMAGE: ${DN_HUB:?err}/dn-perception
    image: ${DN_HUB:?err}/dn-perception-libpointmatcher:${DN_IMAGE_TAG:?err}
    depends_on:
      - dn-perception

