services:

  # ====Dockerized-NorLab perception ==============================================================
  # ....dn-perception..............................................................................
  dn-perception-main:
    extends:
      file: "../global/docker-compose.global.yaml"
      service: global-service-builder-config
    pull_policy: build
    build:
      context: dn-perception
      args:
#        BASE_IMAGE: ${DN_HUB:?err}/dockerized-norlab-dependencies-full
        BASE_IMAGE: ${DN_HUB:?err}/dockerized-norlab-dependencies-ros2-custom
        BASE_IMAGE_TAG: ${DN_IMAGE_TAG:?err}

  dn-perception:
    extends:
      service: dn-perception-main
    image: ${DN_HUB:?err}/dockerized-norlab-perception:${DN_IMAGE_TAG:?err}
    depends_on:
      - dn-perception-main

  # ....libpointmatcher............................................................................
  dn-perception-libpointmatcher-main:
    extends:
      service: dn-perception-main
    build:
      context: dn-perception-libpointmatcher
      args:
        BASE_IMAGE: ${DN_HUB:?err}/dockerized-norlab-perception
    depends_on:
      - dn-perception

  dn-perception-libpointmatcher-tester:
    extends:
      service: dn-perception-libpointmatcher-main
    build:
      target: test
    depends_on:
      - dn-perception-libpointmatcher-main

  dn-perception-libpointmatcher:
    extends:
      service: dn-perception-libpointmatcher-main
    image: ${DN_HUB:?err}/dockerized-norlab-perception-libpointmatcher:${DN_IMAGE_TAG:?err}
    depends_on:
      - dn-perception-libpointmatcher-main

  # ....icp-mapper..................................................................................
  dn-perception-icp-mapper-main:
    extends:
      service: dn-perception-libpointmatcher-main
    build:
      context: dn-perception-icp-mapper
      args:
        BASE_IMAGE: ${DN_HUB:?err}/dockerized-norlab-perception-libpointmatcher
    depends_on:
      - dn-perception-libpointmatcher

  dn-perception-icp-mapper-tester:
    extends:
      service: dn-perception-icp-mapper-main
    build:
      target: test
    depends_on:
      - dn-perception-icp-mapper-main

  dn-perception-icp-mapper:
    extends:
      service: dn-perception-icp-mapper-main
    image: ${DN_HUB:?err}/dockerized-norlab-perception-icp-mapper:${DN_IMAGE_TAG:?err}
    depends_on:
      - dn-perception-icp-mapper-main

  # ....norlab perception stack.....................................................................
  # ToDo: fixme!! >> libpointmatcher_ros install ↓↓
  dn-perception-norlab-stack-main:
    extends:
      service: dn-perception-icp-mapper-main
    build:
      context: dn-perception-norlab-stack
      args:
        BASE_IMAGE: ${DN_HUB:?err}/dockerized-norlab-perception-icp-mapper
    depends_on:
      - dn-perception-icp-mapper

  dn-perception-norlab-stack-tester:
    extends:
      service: dn-perception-norlab-stack-main
    build:
      target: test
    depends_on:
      - dn-perception-norlab-stack-main

  dn-perception-norlab-stack:
    extends:
      service: dn-perception-norlab-stack-main
    build:
      target: final
    image: ${DN_HUB:?err}/dockerized-norlab-perception-stack:${DN_IMAGE_TAG:?err}
    depends_on:
      - dn-perception-norlab-stack-main
