
ARG BASE_IMAGE
ARG BASE_IMAGE_TAG
FROM ${BASE_IMAGE:?err}:${BASE_IMAGE_TAG:?err} AS base-image
WORKDIR /opt
# ====Begin========================================================================================



# ====End==========================================================================================
WORKDIR ${DN_DEV_WORKSPACE}
CMD [ "bash" ]

