# ====Fast test service============================================================================

#  dependencies-test:
#    extends:
#      file: ../docker-compose.global.yaml
#      service: global-service-builder-config
#    build:
#      context: .
#      dockerfile: Dockerfile.test
#      args:
#        BASE_IMAGE: nvcr.io/nvidia/l4t-jetpack
#        BASE_IMAGE_TAG: r35.2.1
#    image: ${DN_HUB:?err}/dockerized-norlab-dependencies-test:r35.2.1

services:

# ====Dockerized-NorLab base images================================================================

# ....Base image requiring conda environment migration to ROS2 compatible python environment.......
  base-image-main:
    extends:
      file: "../global/docker-compose.global.yaml"
      service: global-service-builder-config
    build:
      context: ..
      dockerfile: ../Dockerfile.ros-python-compat
      target: base-image
      args:
        BASE_IMAGE: ${DEPENDENCIES_BASE_IMAGE:?err}
        BASE_IMAGE_TAG: ${DEPENDENCIES_BASE_IMAGE_TAG:?err}

  base-image-tester:
    extends:
      service: base-image-main
    build:
      target: base-image-tester
    depends_on:
      - base-image-main

  base-image:
    extends:
      service: base-image-main
    image: ${DN_HUB:?err}/dockerized-norlab-base-image:${DN_IMAGE_TAG:?err}
    build:
      target: final
    depends_on:
      - base-image-main
