# ====Fast test service============================================================================

#  dependencies-test:
#    extends:
#      file: ../../docker-compose.global.yaml
#      service: global-service-builder-config
#    build:
#      context: .
#      dockerfile: Dockerfile.test
#      args:
#        BASE_IMAGE: nvcr.io/nvidia/l4t-jetpack
#        BASE_IMAGE_TAG: r35.2.1
#    image: ${DN_HUB:?err}/dockerized-norlab-dependencies-test:r35.2.1

services:

  # ====Dockerized-NorLab L4T base images==========================================================

  # ....Jetson dusty ml related base images........................................................
  l4t-base-image-main:
    extends:
      file: "../../global/docker-compose.global.yaml"
      service: global-service-builder-base-images-config
    build:
      context: "."
      dockerfile: Dockerfile.l4t.squash
      target: base-image
      args:
        BASE_IMAGE: ${DEPENDENCIES_BASE_IMAGE:?err}
        BASE_IMAGE_TAG: ${DEPENDENCIES_BASE_IMAGE_TAG:?err}
        MIMIC_DEPENDENCIES_BASE_IMAGE: ${MIMIC_DEPENDENCIES_BASE_IMAGE:?err}
        MIMIC_DEPENDENCIES_BASE_IMAGE_TAG: ${MIMIC_DEPENDENCIES_BASE_IMAGE_TAG:?err}
      platforms: !reset []

  # ....intermediate...............................................................................

  l4t-base-image-arm64:
    extends:
      service: l4t-base-image-main
    build:
      target: base-image-arm64
      args:
        TAG_OS_VERSION: ${TAG_OS_VERSION:?err}
        # Base image env var transfer ('nvcr.io/nvidia/l4t-jetpack' specific)
        CUDA_HOME: ${BASE_IMG_ENV_CUDA_HOME:?err}
        NVIDIA_VISIBLE_DEVICES: ${BASE_IMG_ENV_NVIDIA_VISIBLE_DEVICES:?err}
        NVIDIA_DRIVER_CAPABILITIES: ${BASE_IMG_ENV_NVIDIA_DRIVER_CAPABILITIES:?err}
        PATH: ${BASE_IMG_ENV_PATH:?err}
        LD_LIBRARY_PATH: ${BASE_IMG_ENV_LD_LIBRARY_PATH:?err}
        # The following env var does not appear in every jetson-container 'dustynv' base images
        OPENBLAS_CORETYPE: ${BASE_IMG_ENV_OPENBLAS_CORETYPE}
        LD_PRELOAD: ${BASE_IMG_ENV_LD_PRELOAD}
        # Base image env var transfer (jetson-container pytorch related)
        TORCH_HOME: ${BASE_IMG_ENV_TORCH_HOME}
      platforms:
        - linux/arm64
    depends_on:
      - l4t-base-image-main

  l4t-base-image-amd64:
    extends:
      service: l4t-base-image-main
    build:
      target: base-image-amd64
      platforms:
        - linux/amd64
    depends_on:
      - l4t-base-image-main


  # ....specialization.............................................................................

  l4t-base-image-mimic-l4t-image:
    extends:
      service: l4t-base-image-main
    build:
      target: mimic-l4t-image
      platforms:
        - linux/amd64
    depends_on:
      - l4t-base-image-amd64


  # ....final......................................................................................

  l4t-base-image-final-arm64:
    extends:
      service: l4t-base-image-main
    image: ${DN_HUB:?err}/dockerized-norlab-base-image:${DN_IMAGE_TAG:?err}-arm64
    build:
      target: final-arm64
      platforms:
        - linux/arm64
    depends_on:
      - l4t-base-image-arm64

  l4t-base-image-final-amd64:
    extends:
      service: l4t-base-image-main
    image: ${DN_HUB:?err}/dockerized-norlab-base-image:${DN_IMAGE_TAG:?err}-amd64
    build:
      target: final-amd64
      platforms:
        - linux/amd64
    depends_on:
      - l4t-base-image-mimic-l4t-image

  # ....tests......................................................................................

  l4t-base-image-multiarch-tester:
    extends:
      service: l4t-base-image-main
    build:
      target: test
      platforms:
        - linux/arm64
        - linux/amd64
    depends_on:
      - l4t-base-image-final-amd64
      - l4t-base-image-final-arm64



