
ARG BASE_IMAGE
ARG BASE_IMAGE_TAG
FROM ${BASE_IMAGE:?err}:${BASE_IMAGE_TAG:?err} AS base-image
ARG DEBIAN_FRONTEND=noninteractive

# ====Begin=============================================================================================



# ====End===============================================================================================
CMD [ "bash" ]

