name: ${DN_TARGET_COMPOSE_PROJECT_NAME}

services:

  # ====Dockerized-NorLab control =================================================================
  dn-control:
    extends:
      file: ../compose-matrix/docker-compose.global-service.build.yaml
      service: global-service-builder
    build:
      context: ../core-images/pkg-control/dn-control/
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: ${DN_HUB:?err}/dn-dependencies
        BASE_IMAGE_TAG: ${DN_IMAGE_TAG:?err}
    image: ${DN_HUB:?err}/dn-control:${DN_IMAGE_TAG:?err}

  dn-control-deep-rl:
    extends: dn-control
    build:
      context: ../core-images/pkg-control/dn-control-deep-rl
      args:
        BASE_IMAGE: ${DN_HUB:?err}/dn-control
    image: ${DN_HUB:?err}/dn-control-deep-rl:${DN_IMAGE_TAG:?err}

  dn-control-deep-rl-gym:
    extends: dn-control
    build:
      context: ../core-images/pkg-control/dn-control-deep-rl-gym/
      args:
        BASE_IMAGE: ${DN_HUB:?err}/dn-control-deep-rl
    image: ${DN_HUB:?err}/dn-control-deep-rl-gym:${DN_IMAGE_TAG:?err}

