name: ${DN_TARGET_COMPOSE_PROJECT_NAME}

services:

  # ====Project level==============================================================================
  dn-project-template:
    extends:
      file: ../compose-matrix/docker-compose.global-service.build.yaml
      service: global-service-builder
    build:
      context: ../core-images/project-template
      dockerfile: Dockerfile
      args:
        DN_HUB: ${DN_HUB:?err}   # norlabsnow
        BASE_IMAGE: ${DN_HUB:?err}/dn-control-deep-rl-gym
        BASE_IMAGE_TAG: ${DN_IMAGE_TAG:?err}
        DN_TARGET_PROJECT_SRC_DOMAIN: ${DN_TARGET_PROJECT_SRC_DOMAIN}   # norlab-ulaval
        DN_TARGET_PROJECT_SRC_REPO: ${DN_TARGET_PROJECT_SRC_REPO}   # NorLab_MPPI
    image: ${DN_PROJECT_HUB:?err}/${DN_PROJECT_IMAGE_NAME:?err}:${DN_IMAGE_TAG:?err}
    environment:
      DN_CONTAINER_NAME: ${CONTAINER_NAME}
    container_name: ${CONTAINER_NAME}

  project-develop:
    extends: dn-project-template
    build:
      context: ../core-images/project-develop
      args:
        DN_PROJECT_HUB: ${DN_PROJECT_HUB}   # norlabsnow
        DN_PROJECT_IMAGE_NAME: ${DN_PROJECT_IMAGE_NAME}   # norlab-ros-project-template
        DN_BASE_IMG_TAG: ${DN_IMAGE_TAG:?err}
#        DN_TARGET_PROJECT_SRC_DOMAIN: ${DN_TARGET_PROJECT_SRC_DOMAIN}
#        DN_TARGET_PROJECT_SRC_REPO: ${DN_TARGET_PROJECT_SRC_REPO}
    environment:
      DN_ACTIVATE_POWERLINE_PROMT: true
      DN_CONTAINER_NAME: IamProject
      container_name: IamProject
    image: ${DN_PROJECT_HUB}/${DN_PROJECT_IMAGE_NAME}-develop:${DN_IMAGE_TAG:?err}

#  project-deploy:
#    extends: dependencies-core
#    build:
#      context: ../core-images/project-deploy
#      args:
#         DN_PROJECT_HUB: ${DN_PROJECT_HUB}   # norlabsnow
#         DN_PROJECT_IMAGE_NAME: ${DN_PROJECT_IMAGE_NAME}   # norlab-ros-project-template
#         DN_BASE_IMG_TAG: ${DN_IMAGE_TAG:?err}
##         DS_HOST_TYPE: XavierNX # Option: Local (Not used now)
#         DN_DEPLOY_REPO_BRANCH: main  # Option: main, dev or tag version (ie v*.*.*)
#    image: ${DN_PROJECT_HUB}/${DN_PROJECT_IMAGE_NAME}-deploy:${DEPENDENCIES_BASE_IMAGE_TAG:?err}
#
##  project-deploy-bleeding-edge:
##    extends: project-deploy
##    build:
##      args:
##        DN_DEPLOY_REPO_BRANCH: dev
##    image: ${DN_PROJECT_HUB}/${DN_PROJECT_IMAGE_NAME}-deploy:bleeding-edge-${DEPENDENCIES_BASE_IMAGE_TAG:?err}
#
#
