# ====Fast test service============================================================================

#  dependencies-test:
#    extends:
#      file: ../../docker-compose.global.yaml
#      service: global-service-builder-config
#    build:
#      context: .
#      dockerfile: Dockerfile.test
#      args:
#        BASE_IMAGE: nvcr.io/nvidia/l4t-jetpack
#        BASE_IMAGE_TAG: r35.2.1
#    image: ${DN_HUB:?err}/dockerized-norlab-dependencies-test:r35.2.1

services:

  # ====Dockerized-NorLab base images================================================================

  # ....Jetson dusty ml related base images..........................................................
  base-image-squash-main:
    extends:
      file: "../../global/docker-compose.global.yaml"
      service: global-service-builder-config
    build:
      context: "."
      dockerfile: Dockerfile.cuda.squash
      target: squash-base-image
      args:
        BASE_IMAGE: ${DEPENDENCIES_BASE_IMAGE:?err}
        BASE_IMAGE_TAG: ${DEPENDENCIES_BASE_IMAGE_TAG:?err}
        TAG_OS_VERSION: ${TAG_OS_VERSION:?err}
        UBUNTU_VERSION_MAJOR: ${UBUNTU_VERSION_MAJOR:?err}
        # Base image env var transfer ('nvcr.io/nvidia/l4t-jetpack' specific)
        CUDA_HOME: ${BASE_IMG_ENV_CUDA_HOME:?err}
        NVIDIA_VISIBLE_DEVICES: ${BASE_IMG_ENV_NVIDIA_VISIBLE_DEVICES:?err}
        NVIDIA_DRIVER_CAPABILITIES: ${BASE_IMG_ENV_NVIDIA_DRIVER_CAPABILITIES:?err}
        PATH: ${BASE_IMG_ENV_PATH:?err}
        LD_LIBRARY_PATH: ${BASE_IMG_ENV_LD_LIBRARY_PATH:?err}
        # The following env var does not appear in every jetson-container 'dustynv' base images
        OPENBLAS_CORETYPE: ${BASE_IMG_ENV_OPENBLAS_CORETYPE}
        LD_PRELOAD: ${BASE_IMG_ENV_LD_PRELOAD}
        # Base image env var transfer (jetson-container pytorch related)
        TORCH_HOME: ${BASE_IMG_ENV_TORCH_HOME}
        # Base image env var transfer (jetson-container tensorflow related)
        PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION: ${BASE_IMG_ENV_PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION}
        TENSORBOARD_PORT: ${BASE_IMG_ENV_TENSORBOARD_PORT}
        JUPYTER_PORT: ${BASE_IMG_ENV_JUPYTER_PORT}
        CMAKE_PREFIX_PATH: ${CMAKE_PREFIX_PATH}

#   # ....intermediate...............................................................................
#
#  base-image-ros2-python-compatible-l4t:
#    extends:
#      service: base-image-squash-main
#    build:
#      target: ros2-python-compatible
#      args:
#        PATH: ${BASE_IMG_ENV_PATH:?err}
##      platforms:
##        - linux/arm64
#    depends_on:
#      - base-image-squash-main
#
#  base-image-linux-amd64-mimic-l4t-images:
#    extends:
#      service: base-image-squash-main
#    build:
##      target: linux-amd64-mimic-l4t-images
#      target: final-amd64
#      args:
#        PATH: ${BASE_IMG_ENV_PATH:?err}
#      platforms:
#        - linux/amd64
#    depends_on:
#      - base-image-squash-main

  # ....tests......................................................................................

#  base-image-squash-tester-l4t:
#    extends:
#      service: base-image-squash-main
#    build:
#      target: test
##      platforms:
##        - linux/arm64
#    depends_on:
#      - base-image-ros2-python-compatible-l4t
#
#  base-image-squash-tester-linux:
#    extends:
#      service: base-image-squash-main
#    build:
#      target: test
##      platforms:
##        - linux/amd64
#    depends_on:
#      - base-image-linux-amd64-mimic-l4t-images

  base-image-squash-tester:
    extends:
      service: base-image-squash-main
    build:
      target: test
#      platforms:
#        - linux/amd64
#    depends_on:
#      - base-image-squash-main

#  # ....final......................................................................................
#  base-image-squash-l4t:
#    extends:
#      service: base-image-squash-main
#    image: ${DN_HUB:?err}/dockerized-norlab-base-image:${DN_IMAGE_TAG:?err}
#    build:
#      target: final
##      platforms:
##        - linux/arm64
#    depends_on:
#      - base-image-ros2-python-compatible-l4t
#
#  base-image-squash-linux:
#    extends:
#      service: base-image-squash-main
#    image: ${DN_HUB:?err}/dockerized-norlab-base-image:${DN_IMAGE_TAG:?err}
#    build:
#      target: final
##      platforms:
##        - linux/amd64
#    depends_on:
#      - base-image-linux-amd64-mimic-l4t-images
