#!/bin/bash
# =================================================================================================
# Bash wrapper tailormade for the ssh server user used for remote IDE debugging.
#
# Usage in Dockerfile:
#   SHELL ["/usr/local/bin/bash-dn-ssh-user", "-c"]
#   RUN echo "command executed in bash-dn-ssh-user"
#
# Usage in script:
#   $ usermod --shell /usr/local/bin/bash-dn-ssh-user "${DN_SSH_SERVER_USER}"
#
# Options:
#   any bash flag
#
# Positional argument:
#   Instructions in RUN, CMD or ENTRYPOINT are passed to the '-c' flag.
#
# =================================================================================================
function dn::bash_dn_ssh_server_user() {
  local bash_run_config_root="/dockerized-norlab/dockerized-norlab-images/container-tools/bash_run_config"

  # (CRITICAL) ToDo: assess using this line (ref task NMO-770) ↓ instead of sourcing it.
  export BASH_ENV="${bash_run_config_root}/.bashrc.dn_non_interactive_ssh"

  # ....Execute commands...........................................................................
  if [[ ${debug_log} == true ]]; then
    echo -e "Executing $ \033[1;2mexec bash ${cmds[*]}${MSG_END_FORMAT}\033[0m"
  fi
  exec bash "$@" || return 1
  return 0
}

dn::bash_dn_ssh_server_user "$@" || exit 1
