
services:

  global-service-builder-config:
#    extends: # ToDo: on dev task end >> mute next bloc ↓↓
#      file: ../docker-compose.global.yaml
#      service: global-service-dev-config
    build:
      context: ../global
      dockerfile: ../global/Dockerfile.global
      additional_contexts:
        context-dn-container-tools: ../../container-tools/
        context-dn-submodules: ../../../utilities/
        context-dn-root: ../../../
      args:
        IS_TEAMCITY_RUN: ${IS_TEAMCITY_RUN}
        TARGET_DEVICE: jetson
      platforms:
        - linux/arm64
      labels:
        org.opencontainers.image.authors: "luc.coupal.1@ulaval.ca"
    pull_policy: missing # Note: enforce pulling image only if not available in cache

  # ====Fast test service==========================================================================
#  dependencies-test:
#    extends:
#      file: ../docker-compose.global.yaml
#      service: global-service-builder-config
#    build:
#      context: .
#      dockerfile: Dockerfile.test
#      args:
#        BASE_IMAGE: nvcr.io/nvidia/l4t-jetpack
#        BASE_IMAGE_TAG: r35.2.1
#    image: ${DN_HUB:?err}/dockerized-norlab-dependencies-test:r35.2.1

  # ====Dockerized-NorLab base images==============================================================

  # ....Jetson dusty ml related base images........................................................
  base-image-squash-main: # ›› no push build service
    extends: global-service-builder-config
    build:
      context: .
      dockerfile: Dockerfile.ml.squash
      target: squash-base-image
      args:
        BASE_IMAGE: ${DEPENDENCIES_BASE_IMAGE:?err}
        BASE_IMAGE_TAG: ${DEPENDENCIES_BASE_IMAGE_TAG:?err}
        TAG_OS_VERSION: ${TAG_OS_VERSION:?err}
        # Base image env var transfer ('nvcr.io/nvidia/l4t-jetpack' specific)
        CUDA_HOME: ${BASE_IMG_ENV_CUDA_HOME:?err}
        NVIDIA_VISIBLE_DEVICES: ${BASE_IMG_ENV_NVIDIA_VISIBLE_DEVICES:?err}
        NVIDIA_DRIVER_CAPABILITIES: ${BASE_IMG_ENV_NVIDIA_DRIVER_CAPABILITIES:?err}
        PATH: ${BASE_IMG_ENV_PATH:?err}
        LD_LIBRARY_PATH: ${BASE_IMG_ENV_LD_LIBRARY_PATH:?err}
        # The following env var does not appear in every jetson-container 'dustynv' base images
        OPENBLAS_CORETYPE: ${BASE_IMG_ENV_OPENBLAS_CORETYPE}
        LD_PRELOAD: ${BASE_IMG_ENV_LD_PRELOAD}
        # Base image env var transfer (jetson-container pytorch related)
        TORCH_HOME: ${BASE_IMG_ENV_TORCH_HOME}
        # Base image env var transfer (jetson-container tensorflow related)
        PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION: ${BASE_IMG_ENV_PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION}

  base-image-squash-tester:
    extends: base-image-squash-main
    build:
      target: squashed-base-image-tester
    depends_on:
      - base-image-squash-main

  base-image-squash:
    extends: base-image-squash-main
    image: ${DN_HUB:?err}/dockerized-norlab-base-image-squashed:${DN_IMAGE_TAG:?err}
    build:
      target: final
    depends_on:
      - base-image-squash-main
